version: 2

models:
  - name: fact_bike_trips
    description: fact bike data

  - name: dim_bike_types
    description: bike types
  
  - name: dim_bike_membership
    description: membership subscription

  - name: dim_stations
    description: Contains information on bike stations